export const VttOutputMessageTypes = [
	"MouseStates",
	"ConnectedUserIds",
	"PostPing",
	"VttSceneSnapshot",
	"VttDiceResult",
	"VttChatMessage",
	"VttAllChatMessages",
	"VttAllDiceResults",
	"VttDeleteChatMessage",
	"VttCompleteSceneSnapshot",
	"VttGridMapAdded",
	"VttGridMapUpdated",
	"VttGridMapRemoved",
	"VttGridMapDragStarted",
	"VttGridMapDragUpdate",
	"VttGridMapDragEnded",
	"VttGridMapDragCanceled",
] as const;
export type VttOutputMessageType = (typeof VttOutputMessageTypes)[number];
