// This file is generated automatically. Do not edit it manually.
import { LintIgnoredAny } from "@/libs/stp@types";

export const metadataMap: Record<string, () => Promise<LintIgnoredAny>> = {
  '/changelogs/[version]': () => import('@/app/(site)/changelogs/[version]/page'),
  '/changelogs': () => import('@/app/(site)/changelogs/page'),
  '/chars/[charId]': () => import('@/app/(site)/chars/[charId]/page'),
  '/chars': () => import('@/app/(site)/chars/page'),
  '/codex/[...path]': () => import('@/app/(site)/codex/[...path]/page'),
  '/codex/from-id/[pageId]': () => import('@/app/(site)/codex/from-id/[pageId]/page'),
  '/codex': () => import('@/app/(site)/codex/page'),
  '/home': () => import('@/app/(site)/home/page'),
  '/items/[itemSlug]/edit': () => import('@/app/(site)/items/[itemSlug]/edit/page'),
  '/items/[itemSlug]': () => import('@/app/(site)/items/[itemSlug]/page'),
  '/items/create': () => import('@/app/(site)/items/create/page'),
  '/items': () => import('@/app/(site)/items/page'),
  '/maestrias/[masterySlug]/edit': () => import('@/app/(site)/maestrias/[masterySlug]/edit/page'),
  '/maestrias/[masterySlug]': () => import('@/app/(site)/maestrias/[masterySlug]/page'),
  '/maestrias/create': () => import('@/app/(site)/maestrias/create/page'),
  '/maestrias': () => import('@/app/(site)/maestrias/page'),
  '/racas/[raceSlug]/edit': () => import('@/app/(site)/racas/[raceSlug]/edit/page'),
  '/racas/[raceSlug]': () => import('@/app/(site)/racas/[raceSlug]/page'),
  '/racas/create': () => import('@/app/(site)/racas/create/page'),
  '/racas': () => import('@/app/(site)/racas/page'),
  '/sandbox': () => import('@/app/(site)/sandbox/page'),
  '/skills/[skillSlug]/edit': () => import('@/app/(site)/skills/[skillSlug]/edit/page'),
  '/skills/[skillSlug]': () => import('@/app/(site)/skills/[skillSlug]/page'),
  '/skills/create': () => import('@/app/(site)/skills/create/page'),
  '/skills': () => import('@/app/(site)/skills/page'),
  '/spells/[spellSlug]/edit': () => import('@/app/(site)/spells/[spellSlug]/edit/page'),
  '/spells/[spellSlug]': () => import('@/app/(site)/spells/[spellSlug]/page'),
  '/spells/affaiblir': () => import('@/app/(site)/spells/affaiblir/page'),
  '/spells/anagnosi': () => import('@/app/(site)/spells/anagnosi/page'),
  '/spells/aufbringen': () => import('@/app/(site)/spells/aufbringen/page'),
  '/spells/create': () => import('@/app/(site)/spells/create/page'),
  '/spells/gaizao': () => import('@/app/(site)/spells/gaizao/page'),
  '/spells/gollemhag': () => import('@/app/(site)/spells/gollemhag/page'),
  '/spells/idaitera': () => import('@/app/(site)/spells/idaitera/page'),
  '/spells/impetum': () => import('@/app/(site)/spells/impetum/page'),
  '/spells/khranitel': () => import('@/app/(site)/spells/khranitel/page'),
  '/spells/migaku': () => import('@/app/(site)/spells/migaku/page'),
  '/spells': () => import('@/app/(site)/spells/page'),
  '/spells/sajak': () => import('@/app/(site)/spells/sajak/page'),
  '/spells/verstand': () => import('@/app/(site)/spells/verstand/page'),
  '/spells/vitaeregio': () => import('@/app/(site)/spells/vitaeregio/page'),
  '/tracos/[traitSlug]/edit': () => import('@/app/(site)/tracos/[traitSlug]/edit/page'),
  '/tracos/[traitSlug]': () => import('@/app/(site)/tracos/[traitSlug]/page'),
  '/tracos/create': () => import('@/app/(site)/tracos/create/page'),
  '/tracos': () => import('@/app/(site)/tracos/page'),
  '/users/[username]': () => import('@/app/(site)/users/[username]/page'),
};
